### ISSUE TITLE
As IP Toolchain for Open Harmony project manager I would like a machine to test Open Harmony buiding system

### ISSUE THREAD

**Issue by LucaMiotto** [noi-techpark/project-solda#27]
- [x] I need an instance with the same specification for the Oniro project to test Open Harmony system
- [x] I need then to give access to the machine via SSH to:
- Martin Rabanser
- Alberto Pianon
- [x] The specifications can be copied from the now inactive solda-oniro machine

**Comment by RudiThoeni** [comment]
In AWS currently we have this instances 

fossology c5a.4xlarge currently running
fossology-leda c5a.4xlarge stopped
oniro-build-matrix c6a.4xlarge stopped
oniro-tiny-gitlab-runner t2.medium  running
arango c5.xlarge stopped

@mrabans what instance you prefer ;)

**Comment by RudiThoeni** [comment]
and which OS ?

**Comment by LucaMiotto** [comment]
@RudiThoeni @mrabans the instance I was referring to is oniro-build-matrix c6a.4xlarge. So it should have same characteristics and same OS (I think was Ubuntu but I'm not sure)

**Comment by mrabans** [comment]
@RudiThoeni @LucaMiotto correct, it was an Ubuntu 20.04 LTS

**Comment by RudiThoeni** [comment]
@LucaMiotto 
Created a Machine c6a.4xlarge with 60 GB gp3 root volume / 500GB gp3 volume with Ubuntu 22.04

added the requested keys should be available at
ssh ubuntu@52.48.180.63
@mrabans  please check if everything as it should be

**Comment by LucaMiotto** [comment]
@RudiThoeni did you have also the key from Alberto? Do I need to ask it or I can already send the IP to him too?

**Comment by RudiThoeni** [comment]
> @RudiThoeni did you have also the key from Alberto? Do I need to ask it or I can already send the IP to him too?

yes added also albertos key

**Comment by mrabans** [comment]
@RudiThoeni it works, thanks
