### ISSUE TITLE
As a developer of the SCA tool I want to download the dockers of the components from DockerHub

### ISSUE THREAD

**Issue by LucaMiotto** [noi-techpark/project-solda#8]
- [x] move all the docker created by @Piiit to DockerHub

**Comment by bertolla** [comment]
Just now I published the new docker images from gitlab to dockerhub:
- https://hub.docker.com/r/noitechpark/fossology-on-steroids
- https://hub.docker.com/r/noitechpark/oss-compliance-toolchain

In the meeting with Peter we decided to plan a meeting on how we will handle the deployment and hosting in the future.
There are 2 things to consider here:
1. Dockerhub does not support automated builds with gitlab(currently just github and bitbucket)
2. We can create custom jenkins pipelines were we do build the needed images and push it to dockerhub
