### ISSUE TITLE
As PM of Project Solda I want a reference implementation of compliance tools pipelines to continuously monitor possible compliance issues

### ISSUE THREAD

**Issue by LucaMiotto** [noi-techpark/project-solda#9]
- [x] implement a reference implementation of two GitLab pipelines for tinfoilhat and aliens4friends tools
- [x] create a shared volume to store cache for bitbake builds and output of aliens4friends

It is this upstream issue --> https://git.ostc-eu.org/OSTC/planning/ip-compliance/-/issues/57

**Comment by Piiit** [comment]
@LucaMiotto Patrick gave me this task to complete it on his regard

**Comment by Piiit** [comment]
@LucaMiotto Finally testing at https://git.ostc-eu.org/oss-compliance/toolchain/aliens4friends/-/pipelines/9901... fingers crossed! Should take about 2 days approx
